{% set version = "2.1.9" %}

package:
  name: bob.learn.libsvm
  version: {{ version }}

source:
  fn: bob.learn.libsvm-{{ version }}.zip
  md5: b6e94eaa941fdca76c248878ace04e84
  url: https://pypi.io/packages/source/b/bob.learn.libsvm/bob.learn.libsvm-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libsvm 3.21|3.21.*
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libsvm 3.21|3.21.*
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.learn.libsvm

  imports:
    - bob
    - bob.learn
    - bob.learn.libsvm

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob's Python bindings to LIBSVM

extra:
  recipe-maintainers:
    - 183amir
